[View in Colaboratory](https://colab.research.google.com/github/Anand-krishnakumar/MLP_Classifier_UCI_Iris_data/blob/master/MLPClassifier_UCI_Iris_data.ipynb)

In [171]:
from sklearn.neural_network import MLPClassifier
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report,confusion_matrix
import pandas as pd
import numpy as np
#url for dataset - Iris data
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# column attributes
names =['sepal_length','sepal_width','petal_length', 'petal_width','class']
# df is the dataframa
df = pd.read_csv(url, names=names)
#splitting the input and output as X, y
X = df.iloc[:,:].drop(['class'], axis = 1)
y = df['class']
#splitting the dataset into training and testing data.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 110)

# scaling and transforming the dataset
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

#Found the given combination gave the best results.
mlp = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5), random_state=110, activation='relu', max_iter=200)

mlp.fit(X_train,y_train)
print("Training loss = " + str(mlp.loss_))
print()
predictions = mlp.predict(X_test)

print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

print("Accuracy Score = " + str(accuracy_score(y_test,predictions)))








Training loss = 0.05075986435491307

[[11  0  0]
 [ 0 20  0]
 [ 0  0  7]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      1.00      1.00        20
 Iris-virginica       1.00      1.00      1.00         7

    avg / total       1.00      1.00      1.00        38

Accuracy Score = 1.0
