[View in Colaboratory](https://colab.research.google.com/github/Anand-krishnakumar/MLP_Classifier_UCI_Iris_data/blob/master/MLPClassifier_UCI_Iris_data.ipynb)

In [116]:
from sklearn.neural_network import MLPClassifier
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report,confusion_matrix
import pandas as pd
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
names =['sepal_length','sepal_width','petal_length', 'petal_width','class']
df = pd.read_csv(url, names=names)

df1 = pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data', names = ['Sample code number','Clump Thickness','Uniformity of Cell Size', 'Uniformity of Cell Shape','Marginal Adhesion', 'Single Epithelial Cell Size','Bare Nuclei','Bland Chromatin','Normal Nucleoli','Mitoses','Class'])
X = df.iloc[:,:].drop(['class'], axis = 1)
y = df['class']
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 1)
scaler = StandardScaler()
# Fit only to the training data
scaler.fit(X_train)
# Now apply the transformations to the data:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
mlp = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5,5,10), random_state=110, activation='relu', max_iter=200)
mlp.fit(X_train,y_train)
predictions = mlp.predict(X_test)

print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

print("Accuracy Score = " + str(accuracy_score(y_test,predictions)))








[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        13
Iris-versicolor       1.00      0.94      0.97        16
 Iris-virginica       0.90      1.00      0.95         9

    avg / total       0.98      0.97      0.97        38

Accuracy Score = 0.9736842105263158
